# Generated by Django 5.2.7 on 2025-10-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_avatar_color_profile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='job',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
