# Generated by Django 4.2.24 on 2025-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tradesman', 'Tradesman'), ('customer', 'Customer')], default='customer', max_length=15),
        ),
    ]
