# Generated by Django 4.2.24 on 2025-11-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_job_title_remove_profile_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profile',
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=25, max_length=50),
            preserve_default=False,
        ),
    ]
