# Generated by Django 5.2.7 on 2025-11-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_reviewed_review_tradesman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tradesman', 'Tradesman'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=15),
        ),
    ]
